export const events = [
  {
    id: 1,
    title: "Chicken BBQ",
    description: "Fundraiser",
    content: [
      "Get ready for our Fall Chicken BBQ on Sunday, September 8th! This mouth-watering event will take place from noon until 2pm, or until we're sold out. Please note, only 500 tickets will be sold, so be sure to secure yours early!",
      "Each $15.00 ticket includes a hearty meal of ½ chicken, salt potatoes, coleslaw, a roll, and a cookie. Pickup will be at the Attica Elementary School parking lot.",
      "To purchase your tickets, simply click the button below to buy online. Alternatively, tickets are available at our home, located at 91 Main St, Attica. You can also call Sue at (585) 708-4331 to arrange to purchase tickets by cash or check.",
      "Given the popularity of this event, we usually sell out. Therefore, pre-sale is highly encouraged to ensure you don't miss out on this delicious BBQ feast! We look forward to seeing you there!",
    ],
    action: "Buy Tickets",
    link: "https://gatewayhomeattica.networkforgood.com/events/74632-fall-chicken-bbq-sun-sept-8th",
  },
  {
    id: 2,
    title: "End of Life Doula",
    description: "Training Course",
    content: [
      "We are excited to announce an 8-week End of Life Doula training course at Gateway Home, beginning Wednesday, September 18th. This immersive program is designed to empower caregivers with the skills and wisdom to offer compassionate support to those nearing the end of life. The class will take place every Wednesday for eight consecutive weeks, providing both practical and spiritual tools to help those in their final days live fully until they pass.",
      "Course Overview:",
      "This training will be an in-depth exploration of what it means to be a supportive presence in the dying process.",
      "Our sessions will include:",
      "Creating Sacred Space for the Dying: Learn how to transform the environment into a sanctuary that fosters peace and comfort for those transitioning.",
      'Holding Space: Develop the ability to sit with others in their most vulnerable moments, offering quiet, attentive presence without the need to "fix" anything.',
      "Building a Legacy: Discover techniques to help individuals craft a lasting legacy, documenting and preserving their precious memories, stories, and lessons for loved ones.",
      "Holding Vigil: Learn how to lead a vigil, a time-honored tradition of gathering loved ones to witness, support, and honor the dying person during their final moments.",
      "Reprocessing the Death: Gain tools for helping families and friends reprocess the passing of their loved one, finding closure and peace after the loss.",
      "Preserving Precious Memories: Delve into methods for documenting and safeguarding the stories and moments that define a life, creating cherished keepsakes for loved ones to hold onto.",
      "Processing Unfinished Business: Learn to assist individuals in addressing any unresolved issues, facilitating emotional and spiritual healing before they pass.",
      "Why Attend?",
      "This training will be transformative for caregivers who feel called to accompany others during life’s final chapter. Whether you are a professional caregiver, family member, or someone seeking a deeper understanding of the end-of-life process, this course will provide you with the tools and mindset needed to navigate this profound journey with grace and compassion. Classes will take place at Gateway Home each Wednesday evening starting September 18th from 6:00-8:00 pm. Space is limited to ensure a personalized and intimate experience for all participants.",
      "To register or learn more about this program, please contact Sara Brunner. We hope you’ll join us in this meaningful work of supporting others in living fully until their last breath.",
    ],
    action: "Register Now",
    link: "mailto:sara@gatewayhomeattica.org",
  },
  {
    id: 3,
    title: "Meat Raffle",
    description: "Fundraiser",
    content: [
      "Join us on Saturday, September 28, 2024, for an exciting evening at the Alexander Firemen’s Recreation Hall, located at 10708 Alexander Rd, Alexander, NY 14011. Doors will open at 6:00 pm, with the first spin taking place promptly at 7:00 pm.",
      "Presale tickets are available for $10.00 each or $80.00 for a table of 8. Tickets at the door will be $15.00. Each ticket includes one chance for the door prize, a slice of pizza, and a beverage (soda or water).",
      "The evening will feature a Basket Raffle and 50/50 tickets. Feel free to bring snacks to share at your table and a cooler to hold your winnings! Please note, no outside alcohol is permitted.",
      "A cash bar will be available, presented by and benefiting the Alexander Fire Department.",
      "This event is held to benefit Gateway Home Comfort Care, located at 91 Main Street, Attica, NY 14011. For more information, please contact us at 585-708-4331.",
      "We look forward to seeing you there for a night of fun, food, and fundraising!",
    ],
    action: "Buy Tickets",
    link: "https://gatewayhomeattica.networkforgood.com/events/74629-3rd-annual-meat-raffle-sat-9-28",
  },
];
