import { Mail, Map, Phone, Printer, ThumbsUp, UserPlus } from "lucide-react";

export const socials = [
  {
    id: 1,
    title: "Phone",
    description: "585-708-4331",
    link: "tel:585-708-4331",
    icon: Phone,
    action: "Call Us",
  },
  {
    id: 2,
    title: "Email",
    description: "info@gatewayhomeattica.org",
    link: "mailto:info@gatewayhomeattica.org",
    icon: Mail,
    action: "Email Us",
  },
  {
    id: 3,
    title: "Fax",
    description: "585-708-4333",
    link: "fax:5857084333",
    icon: Printer,
    action: "Fax Us",
  },
  {
    id: 4,
    title: "Address",
    description: " 91 Main Street, Attica, NY 14011",
    link: "https://www.google.com/maps/search/?api=1&query=91 Main Street, Attica, NY 14011",
    icon: Map,
    action: "Find Us",
  },
  {
    id: 5,
    title: "Facebook",
    description: "Gateway Home",
    link: "https://www.facebook.com/gatewayhomeattica/",
    icon: ThumbsUp,
    action: "Like Us",
  },
  {
    id: 6,
    title: "Instagram",
    description: "gatewayhomeattica",
    link: "https://www.instagram.com/gatewayhomeattica/",
    icon: UserPlus,
    action: "Follow Us",
  },
];

export const donors = [
  { name: "Attica Lions Club", level: "Platinum" },
  { name: "Attica Package Company, Inc.", level: "Platinum" },
  { name: "Donna Ferry", level: "Platinum" },
  { name: "Louise M Schiltz", level: "Platinum" },
  { name: "Advanced Dairy Services, Inc.", level: "Gold" },
  { name: "Doug & Rosie Domes", level: "Gold" },
  { name: "Dr. Joseph & Marcy Craddock", level: "Gold" },
  { name: "James & Jane Frankenberger", level: "Gold" },
  { name: "L Toal Plumbing, LLC", level: "Gold" },
  { name: "Marley Funeral Home LLC", level: "Gold" },
  { name: "Providence Fellowship", level: "Gold" },
  { name: "Ralph A. Janes", level: "Gold" },
  { name: "Robinson & Hackemer Funeral Home", level: "Gold" },
  { name: "S.J.F. Construction, Inc", level: "Gold" },
  { name: "Shirley Teachen", level: "Gold" },
  { name: "Todd & Brittany Gadd", level: "Gold" },
  { name: "Connie Tartick", level: "Silver" },
  { name: "County Line Stone Co., Inc.", level: "Silver" },
  { name: "Durin Rogers & Paula Campbell", level: "Silver" },
  { name: "Harding's Attica Furniture", level: "Silver" },
  { name: "Joseph & Carol Pilc", level: "Silver" },
  { name: "Michael & Marybeth Whiting", level: "Silver" },
  { name: "Paul & Diane Luderman", level: "Silver" },
  { name: "Ron & Peach Merrill", level: "Silver" },
  { name: "Sandy Ewert", level: "Silver" },
  { name: "Shirley F. Peters", level: "Silver" },
  { name: "Zehler Excavating, LLC", level: "Silver" },
  { name: "Alan & Kelly Heizmann", level: "Bronze" },
  { name: "Alfonso J. Ficarella", level: "Bronze" },
  { name: "Andrew & Carla Gasiewicz", level: "Bronze" },
  { name: "Angela Milillo & Doug Patti", level: "Bronze" },
  { name: "Ann & Deane Foster", level: "Bronze" },
  { name: "Anna Nutty", level: "Bronze" },
  { name: "Arch & Peggy Snyder", level: "Bronze" },
  { name: "Barbara C. Schiltz", level: "Bronze" },
  { name: "Barbara Myers", level: "Bronze" },
  { name: "Bernard & Janet Meinweiser", level: "Bronze" },
  { name: "Brennan & Shelly Burdett", level: "Bronze" },
  { name: "Can Can Redemption", level: "Bronze" },
  { name: "Charles & J. Terri Woodruff", level: "Bronze" },
  { name: "Clarence & Mary Weaver", level: "Bronze" },
  { name: "Connie Holt", level: "Bronze" },
  { name: "Cooke & Steffan - Mr. Tom Steffan", level: "Bronze" },
  { name: "Daniel & Barbara Krazmien", level: "Bronze" },
  { name: "Daniel & Jean Burling", level: "Bronze" },
  { name: "Daniel & Shannon Ford", level: "Bronze" },
  { name: "Daniel & Susan Boss", level: "Bronze" },
  { name: "Dave & Joanne Thornton", level: "Bronze" },
  { name: "David & Connie Rethlake", level: "Bronze" },
  { name: "David & Judith Brockner", level: "Bronze" },
  { name: "Dennis & Carol Piechowiak", level: "Bronze" },
  { name: "Diane Phelps", level: "Bronze" },
  { name: "Don & Jude Carpenter", level: "Bronze" },
  { name: "Don & Patti Almeter", level: "Bronze" },
  { name: "Donald & Linda Schmidt", level: "Bronze" },
  { name: "Donald and Jane Beechler", level: "Bronze" },
  { name: "Empire Access", level: "Bronze" },
  { name: "Gary & Carol Barrow", level: "Bronze" },
  { name: "Gary & Karen Beideck", level: "Bronze" },
  { name: "Gary & Renee Hanley", level: "Bronze" },
  { name: "Gerald & Deborah Landowski", level: "Bronze" },
  { name: "Gina M. Morrison", level: "Bronze" },
  { name: "Grace Strollo", level: "Bronze" },
  { name: "Helen Leonard", level: "Bronze" },
  { name: "Helen Nichols", level: "Bronze" },
  { name: "Herbert Hammond", level: "Bronze" },
  { name: "Howard & Muriel Herman", level: "Bronze" },
  { name: "J & S Agen, Inc. - Design Art", level: "Bronze" },
  { name: "Janet Romesser", level: "Bronze" },
  { name: "Jeannie K. Bates", level: "Bronze" },
  { name: "Jerry & Sue Elmore", level: "Bronze" },
  { name: "Jerilyn Clark", level: "Bronze" },
  { name: "John E. Jaszko", level: "Bronze" },
  { name: "Joseph & Laura Schmieder", level: "Bronze" },
  { name: "Kelly Nelson", level: "Bronze" },
  { name: "Kevin & Lisa Cochrane", level: "Bronze" },
  { name: "Kirk & Nina Reisdorf", level: "Bronze" },
  { name: "Laurie Valenti", level: "Bronze" },
  { name: "Logel Appliance, Inc.", level: "Bronze" },
  { name: "Lor-Rob Dairy Farm", level: "Bronze" },
  { name: "Lynn & Linda Camp", level: "Bronze" },
  { name: "Lynn Herman", level: "Bronze" },
  { name: "Martha Whittington", level: "Bronze" },
  { name: "Matthew & Mary Mest", level: "Bronze" },
  { name: "Melissa Spink", level: "Bronze" },
  { name: "Michael & Peggy Morrissey", level: "Bronze" },
  { name: "Mike & Karen Shadbolt", level: "Bronze" },
  { name: "M&M Meats", level: "Bronze" },
  { name: "Norb & Marilyn Fuest", level: "Bronze" },
  { name: "Norma Gerhardt", level: "Bronze" },
  { name: "Orangeville Immanuel United Church of Chr", level: "Bronze" },
  { name: "Pat Forsha Truck and Auto Collision, Inc.", level: "Bronze" },
  { name: "Patricia Herman", level: "Bronze" },
  { name: "Paul & Carol George", level: "Bronze" },
  { name: "Paul & Maryann Simonsen", level: "Bronze" },
  { name: "Peter & Dawn Mark", level: "Bronze" },
  { name: "Randy & Mary Szczesniak", level: "Bronze" },
  { name: "Richard & Linda VanDette", level: "Bronze" },
  { name: "Richard H. & Maria Walczak", level: "Bronze" },
  { name: "Robert & Barbara Peters", level: "Bronze" },
  { name: "Robert & Eileen Disinger", level: "Bronze" },
  { name: "Robert & Maureen Kirby", level: "Bronze" },
  { name: "Robert A. Koerner Construction", level: "Bronze" },
  { name: "Ronald J. Demers", level: "Bronze" },
  { name: "Rose Bartz", level: "Bronze" },
  { name: "Sandra C. Green", level: "Bronze" },
  { name: "Sandra Urquhart", level: "Bronze" },
  { name: "Sons of the American Legion Post 1720", level: "Bronze" },
  { name: "Springtyme Landscaping & Design Inc.", level: "Bronze" },
  { name: "Stuart & Janis Hempel", level: "Bronze" },
  { name: "Susan Grew", level: "Bronze" },
  { name: "The Greenery", level: "Bronze" },
  { name: "Tim & Louise Royce", level: "Bronze" },
  { name: "Timothy J. & Donna Embt", level: "Bronze" },
  { name: "Toshmin D. Duncan", level: "Bronze" },
  { name: "Virginia & Burt Fugle", level: "Bronze" },
  { name: "Warsaw Pennysaver", level: "Bronze" },
  { name: "Wilkins Insurance Agency, Inc", level: "Bronze" },
  { name: "William Errington", level: "Bronze" },
  { name: "William J. Renz Jr.", level: "Bronze" },
];

export const leadership = [
  {
    id: 1,
    name: "Doug Domes",
    position: "Board President",
    image: "/images/leadership/doug-domes.jpeg",
    bio: [
      "Doug has lived his life as a resident of Attica with wife Rosie of 55 years. He has four children who have blessed him with 16 beautiful grandchildren. As a businessman in the timber industry, Doug knows trees to be God’s only renewable natural resource for all of us to use wisely and has learned to respect this resource.",
      "Doug recognizes the value of a human’s heart, soul, and body and as a result sees “Gateway Home” as a chance to give back or pass onto those in need the blessing God has bestowed on him. He wants to help those who are facing their last days, weeks, or possible months on this earth not fearing their ultimate departure from this earth. Doug believes it is important for them to know they are loved and valued by being cared for physically, emotionally, and spiritually. The bible states the Golden Rule as “Do unto others as you would have them do unto you.” Showing love and caring for others is the means by which we all should live.",
    ],
  },
  {
    id: 2,
    name: "Jim Russell",
    position: "Board Vice President",
    image: "/images/leadership/jim-russell.jpeg",
    bio: [
      "Jim has lived in Batavia for over 50 years, many of which he owned and operated a fire and safety company. He has 3 children and 4 grandchildren. Over the years he has volunteered and served on many committees such as Volunteer Firefighter for the Town of Stafford and Town of Batavia Fire Departments, Batavia City Councilman, City of Batavia Zoning Board and Knights of Columbus Council 11728.",
      "Jim first became involved with Gateway Home in February 2020 when he brought his wife, Judy of 47 years to Gateway Home as her battle with lung cancer was coming to an end. After Judy’s passing Jim wanted to give back to Gateway Home for the support they provided. Jim organized a Chicken BBQ fundraiser that summer at Gateway Home. After that he began serving on the Board of Directors in 2021.  Jim continues to honor Judy’s memory by organizing and cooking two Chicken BBQ fundraisers each year for Gateway Home. In July 2022, he also started the First Annual Judy Russell Memorial Golf Tournament with all the proceeds raised donated to Gateway Home.",
    ],
  },
  {
    id: 3,
    name: "Todd Gadd",
    position: "Board Treasurer",
    image: "/images/leadership/todd-gadd.jpeg",
    bio: [
      "Todd Gadd was led to be involved with a comfort care facility following an opportunity to serve others on a short-term mission trip to the Dominican Republic. This was following the passing of his mother during her illness in which her family had the privilege to take care of her at home until her passing. He has been part of the group that has organized Gateway Home and is now serving on the Board of Directors. Todd is married to Brittany and has two children, Cooper and Chloe. He grew up in Attica and currently lives in Cowlesville, NY. Being involved with such a much-needed organization whose purpose is to only help others has been very rewarding.",
    ],
  },
  {
    id: 4,
    name: "Carolyn Gadd",
    position: "Board Secretary",
    image: "/images/leadership/carolyn-gadd.jpg",
    bio: [
      "Carolyn Gadd lives in Alden, NY with her two daughters Alyssa, and Madison.  She has been a volunteer for Gateway Home since 2016 helping to spread the word of Gateway Home outside of Attica. She has also hosted fundraisers in Alden on behalf of Gateway Home, volunteered at various Gateway events and works at the Darien Lake Concert concession stands to raise money for Gateway.",
      "Carolyn has 25 plus years of experience working in a business environment where her experience is utilized as Treasurer for Gateway Home.",
      "Carolyn feels fortunate to be in an organization that allows her to help others and apply her skills to make a difference in the life of others.",
    ],
  },
  {
    id: 5,
    name: "Donna Ferry",
    position: "Board Member",
    image: "/images/leadership/donna-ferry.jpg",
    bio: [
      "Donna Ferry lives in Darien and retired several years ago from S.J.F. Construction, Inc.  She has volunteered for several organizations that have allowed her to connect with the community including serving on the Board of Trustees at Genesee Community College.   ",
      "After losing her mother to a short illness in 2021 her thoughts turned to the importance of end-of-life care and she began volunteering at Gateway Home in 2022 along with assisting with fundraising endeavors.   ",
      "Serving alongside amazing volunteers and care givers has been a truly humbling experience for Donna and has strengthen her resolve to support Gateway Home in their mission. Donna joined the board in January 2023 and looks forward to working with the staff, volunteers, care givers, and fellow board members.",
    ],
  },
  {
    id: 6,
    name: "Kimberly Kadziolka",
    position: "Board Member",
    image: "/images/placeholder.svg",
    bio: null,
  },
  {
    id: 7,
    name: "Sara Brunner",
    position: "Director",
    image: "/images/leadership/sara-brunner.jpg",
    bio: [
      "Sara's journey to Gateway Home is deeply rooted in her personal experiences and professional background. Residing in Batavia with her beloved family, she found her calling in end-of-life care following the loss of her close friend Wendy. Witnessing the profound impact of love and compassion during Wendy's final moments solidified Sara's commitment to this field.",
      "In February 2023, Sara joined Gateway Home as an overnight aide, while continuing her role as a volunteer coordinator at Crossroads House during the day. Her transition from hospitality management to end-of-life care reflects her dedication to providing meaningful support to families. Sara is excited to leverage her empathy and leadership skills at Gateway Home, aiming to expand its reach and positively impact as many lives as possible.",
    ],
  },
  {
    id: 8,
    name: "Sue Herman",
    position: "Office Manager",
    image: "/images/leadership/sue-herman.jpeg",
    bio: [
      "Sue joined our team when we opened our doors in December 2019 and handles the day to day office tasks such as bookkeeping, mail and telephone. She also helps coordinate our volunteer scheduling and is often the voice behind the One Call messaging system. She is a graduate of Canisius College and is a certified public accountant. She previously worked for Farm Credit East as an agricultural income tax preparer. Sue keeps her hands in agriculture by continuing to do some on-farm bookkeeping as time permits. She enjoys volunteering with Attica Youth Athletics and is a member of the Attica Central School Board of Education.",
      "Sue lives in Attica with her husband, Don and son, Isaac. Sue and Don also have 3 adult children and 4 grandchildren. She is excited to add her creativity and enthusiasm to help promote Gateway Home’s mission.",
    ],
  },
];
